// <auto-generated />
using System;
using System.Text.Json;
using FixMessageAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FixMessageAnalyzer.Migrations
{
    [DbContext(typeof(FixDbContext))]
    [Migration("20250303054721_EnhancedFixMessageSchema")]
    partial class EnhancedFixMessageSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fix")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FixMessageAnalyzer.Data.Entities.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_connectors_is_active");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_connectors_type");

                    b.ToTable("connectors", "fix");
                });

            modelBuilder.Entity("FixMessageAnalyzer.Data.Entities.FixMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account");

                    b.Property<string>("ClOrdID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cl_ord_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CumQty")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("cum_qty");

                    b.Property<string>("ExecID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exec_id");

                    b.Property<string>("ExecType")
                        .HasColumnType("text");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FixVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fix_version");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_valid");

                    b.Property<decimal?>("LastQty")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("last_qty");

                    b.Property<decimal?>("LeavesQty")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("leaves_qty");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("msg_type");

                    b.Property<string>("MsgTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("msg_type_name");

                    b.Property<string>("OrdStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ord_status");

                    b.Property<string>("OrdType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ord_type");

                    b.Property<string>("OrderID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("OrderQty")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("order_qty");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("price");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("security_type");

                    b.Property<string>("SenderCompID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_comp_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)")
                        .HasColumnName("session_id")
                        .HasComputedColumnSql("sender_comp_id || '-' || target_comp_id", true);

                    b.Property<string>("Side")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<string>("TargetCompID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_comp_id");

                    b.Property<string>("TimeInForce")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("time_in_force");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("TransactTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transact_time");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id");

                    b.HasIndex("ClOrdID")
                        .HasDatabaseName("idx_messages_cl_ord_id");

                    b.HasIndex("MsgType")
                        .HasDatabaseName("idx_messages_msg_type");

                    b.HasIndex("OrdStatus")
                        .HasDatabaseName("idx_messages_ord_status");

                    b.HasIndex("SenderCompID")
                        .HasDatabaseName("idx_messages_sender");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_messages_session_id");

                    b.HasIndex("Side")
                        .HasDatabaseName("idx_messages_side");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_messages_symbol");

                    b.HasIndex("TargetCompID")
                        .HasDatabaseName("idx_messages_target");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_messages_timestamp");

                    b.ToTable("messages", "fix");
                });
#pragma warning restore 612, 618
        }
    }
}
