services:
  backend:
    container_name: fix-backend
    build: ../backend
    ports:
      - "9090:8080"
    environment:
      - ConnectionStrings__pgsqlconnection=Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Port=${DB_PORT}
    depends_on:
      - frontend
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  database:
    build: 
      context: ../database
      dockerfile: pgDockerfile
    environment:
      POSTGRES_DB: quantscopedb
      POSTGRES_USER: quantuser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-quantpassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantuser -d quantscopedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    build: ../frontend
    environment:
          - VITE_API_BASE_URL=http://localhost:9090/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: