name: Deploy QuantScope App

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Set the environment name here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t your-dockerhub-username/fix-backend:latest ./backend
          docker push your-dockerhub-username/fix-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t your-dockerhub-username/fix-frontend:latest ./frontend
          docker push your-dockerhub-username/fix-frontend:latest

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.ORACLE_VM_USER }}/app

            # Pull latest images
            docker pull your-dockerhub-username/fix-backend:latest
            docker pull your-dockerhub-username/fix-frontend:latest

            # Stop and remove existing containers
            docker-compose down

            # Start only frontend & backend (excluding database)
            docker-compose up -d backend frontend
